// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package microservice

import (
	"backend/api/microservice"
)

type ControllerV1 struct{}

func NewV1() microservice.IMicroserviceV1 {
	return &ControllerV1{}
}
