// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package project

import (
	"backend/api/project"
)

type ControllerV1 struct{}

func NewV1() project.IProjectV1 {
	return &ControllerV1{}
}
