// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// internalFunctionDao is internal type for wrapping internal DAO implements.
type internalFunctionDao = *internal.FunctionDao

// functionDao is the data access object for table function.
// You can define custom methods on it to extend its functionality as you wish.
type functionDao struct {
	internalFunctionDao
}

var (
	// Function is globally public accessible object for table function operations.
	Function = functionDao{
		internal.NewFunctionDao(),
	}
)

// Fill with you ideas below.
