// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// internalLineEntryDao is internal type for wrapping internal DAO implements.
type internalLineEntryDao = *internal.LineEntryDao

// lineEntryDao is the data access object for table line_entry.
// You can define custom methods on it to extend its functionality as you wish.
type lineEntryDao struct {
	internalLineEntryDao
}

var (
	// LineEntry is globally public accessible object for table line_entry operations.
	LineEntry = lineEntryDao{
		internal.NewLineEntryDao(),
	}
)

// Fill with you ideas below.
