// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// internalMappingDao is internal type for wrapping internal DAO implements.
type internalMappingDao = *internal.MappingDao

// mappingDao is the data access object for table mapping.
// You can define custom methods on it to extend its functionality as you wish.
type mappingDao struct {
	internalMappingDao
}

var (
	// Mapping is globally public accessible object for table mapping operations.
	Mapping = mappingDao{
		internal.NewMappingDao(),
	}
)

// Fill with you ideas below.
