// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// internalMicroserviceDao is internal type for wrapping internal DAO implements.
type internalMicroserviceDao = *internal.MicroserviceDao

// microserviceDao is the data access object for table microservice.
// You can define custom methods on it to extend its functionality as you wish.
type microserviceDao struct {
	internalMicroserviceDao
}

var (
	// Microservice is globally public accessible object for table microservice operations.
	Microservice = microserviceDao{
		internal.NewMicroserviceDao(),
	}
)

// Fill with you ideas below.
