// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// internalMicroservicesDao is internal type for wrapping internal DAO implements.
type internalMicroservicesDao = *internal.MicroservicesDao

// microservicesDao is the data access object for table microservices.
// You can define custom methods on it to extend its functionality as you wish.
type microservicesDao struct {
	internalMicroservicesDao
}

var (
	// Microservices is globally public accessible object for table microservices operations.
	Microservices = microservicesDao{
		internal.NewMicroservicesDao(),
	}
)

// Fill with you ideas below.
