// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// internalProfileCommentDao is internal type for wrapping internal DAO implements.
type internalProfileCommentDao = *internal.ProfileCommentDao

// profileCommentDao is the data access object for table profile_comment.
// You can define custom methods on it to extend its functionality as you wish.
type profileCommentDao struct {
	internalProfileCommentDao
}

var (
	// ProfileComment is globally public accessible object for table profile_comment operations.
	ProfileComment = profileCommentDao{
		internal.NewProfileCommentDao(),
	}
)

// Fill with you ideas below.
