// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// internalProfileDao is internal type for wrapping internal DAO implements.
type internalProfileDao = *internal.ProfileDao

// profileDao is the data access object for table profile.
// You can define custom methods on it to extend its functionality as you wish.
type profileDao struct {
	internalProfileDao
}

var (
	// Profile is globally public accessible object for table profile operations.
	Profile = profileDao{
		internal.NewProfileDao(),
	}
)

// Fill with you ideas below.
