// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// internalSampleDao is internal type for wrapping internal DAO implements.
type internalSampleDao = *internal.SampleDao

// sampleDao is the data access object for table sample.
// You can define custom methods on it to extend its functionality as you wish.
type sampleDao struct {
	internalSampleDao
}

var (
	// Sample is globally public accessible object for table sample operations.
	Sample = sampleDao{
		internal.NewSampleDao(),
	}
)

// Fill with you ideas below.
