// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// internalSampleLabelDao is internal type for wrapping internal DAO implements.
type internalSampleLabelDao = *internal.SampleLabelDao

// sampleLabelDao is the data access object for table sample_label.
// You can define custom methods on it to extend its functionality as you wish.
type sampleLabelDao struct {
	internalSampleLabelDao
}

var (
	// SampleLabel is globally public accessible object for table sample_label operations.
	SampleLabel = sampleLabelDao{
		internal.NewSampleLabelDao(),
	}
)

// Fill with you ideas below.
