// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// internalSampleNumlabelDao is internal type for wrapping internal DAO implements.
type internalSampleNumlabelDao = *internal.SampleNumlabelDao

// sampleNumlabelDao is the data access object for table sample_numlabel.
// You can define custom methods on it to extend its functionality as you wish.
type sampleNumlabelDao struct {
	internalSampleNumlabelDao
}

var (
	// SampleNumlabel is globally public accessible object for table sample_numlabel operations.
	SampleNumlabel = sampleNumlabelDao{
		internal.NewSampleNumlabelDao(),
	}
)

// Fill with you ideas below.
