// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// internalSampleLocationDao is internal type for wrapping internal DAO implements.
type internalSampleLocationDao = *internal.SampleLocationDao

// sampleLocationDao is the data access object for table sample_location.
// You can define custom methods on it to extend its functionality as you wish.
type sampleLocationDao struct {
	internalSampleLocationDao
}

var (
	// SampleLocation is globally public accessible object for table sample_location operations.
	SampleLocation = sampleLocationDao{
		internal.NewSampleLocationDao(),
	}
)

// Fill with you ideas below.
