// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// internalSampleValueDao is internal type for wrapping internal DAO implements.
type internalSampleValueDao = *internal.SampleValueDao

// sampleValueDao is the data access object for table sample_value.
// You can define custom methods on it to extend its functionality as you wish.
type sampleValueDao struct {
	internalSampleValueDao
}

var (
	// SampleValue is globally public accessible object for table sample_value operations.
	SampleValue = sampleValueDao{
		internal.NewSampleValueDao(),
	}
)

// Fill with you ideas below.
