// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// internalSampleTypeDao is internal type for wrapping internal DAO implements.
type internalSampleTypeDao = *internal.SampleTypeDao

// sampleTypeDao is the data access object for table sample_type.
// You can define custom methods on it to extend its functionality as you wish.
type sampleTypeDao struct {
	internalSampleTypeDao
}

var (
	// SampleType is globally public accessible object for table sample_type operations.
	SampleType = sampleTypeDao{
		internal.NewSampleTypeDao(),
	}
)

// Fill with you ideas below.
