// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// internalTestRecordsDao is internal type for wrapping internal DAO implements.
type internalTestRecordsDao = *internal.TestRecordsDao

// testRecordsDao is the data access object for table test_records.
// You can define custom methods on it to extend its functionality as you wish.
type testRecordsDao struct {
	internalTestRecordsDao
}

var (
	// TestRecords is globally public accessible object for table test_records operations.
	TestRecords = testRecordsDao{
		internal.NewTestRecordsDao(),
	}
)

// Fill with you ideas below.
