// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// internalValuetypeDao is internal type for wrapping internal DAO implements.
type internalValuetypeDao = *internal.ValuetypeDao

// valuetypeDao is the data access object for table valuetype.
// You can define custom methods on it to extend its functionality as you wish.
type valuetypeDao struct {
	internalValuetypeDao
}

var (
	// Valuetype is globally public accessible object for table valuetype operations.
	Valuetype = valuetypeDao{
		internal.NewValuetypeDao(),
	}
)

// Fill with you ideas below.
